### ISSUE TITLE
ansible install script fails if old directories of previous version are still present

### ISSUE THREAD

**Issue by stevenvanrossem** [mpeuster/containernet#11]
the install yml script fails if these directories already exist in the install directory:
The failure occurs during containernet/util/install.sh
(these dirs can exist because of a previous install of containernet/dockernet) 
*openflow
*loxigen
*pox
*oftest
*oflops
After manually removing these directories, install script works out of the box.
Should these directories be removed by the install script first?

**Comment by mpeuster** [comment]
Yes, we should remove them. I assume this also happens with the default Mininet installation.
