### ISSUE TITLE
the sudo ansible-playbook install.yml is failed

### ISSUE THREAD

**Issue by intidharbedhief** [mpeuster/containernet#14]
when i execute the sudo ansible-playbook install.yml command an error is appeared "all hosts are already  failed  
![image](https://cloud.githubusercontent.com/assets/19667660/17858622/ac9b7f20-6886-11e6-8fe9-d47cc9164f07.png)

**Comment by intidharbedhief** [comment]
![image](https://cloud.githubusercontent.com/assets/19667660/17858874/bba49f32-6887-11e6-91e0-2f160f031a4f.png)

**Comment by mpeuster** [comment]
The error is an issue with your APT system: `apt-get update` seem to fail.

What OS are you using? 
- The installation requires a (fresh!) Ubuntu 14.04 LTS installation

Is Mininet already installed?
- You must not use the Mininet VM provided by the Mininet webpage. If Mininet is already installed on the system, the script will fail as well (again, it requires a fresh Ubuntu installation).

**Comment by intidharbedhief** [comment]
Thank you for the response, it seems that the problem is because i am using Mininet VM  :(

**Comment by mpeuster** [comment]
Yes. Just install a fresh Ubuntu VM and the script will work.

Close.
